### ISSUE TITLE
LeakCanary shows leaks on standard usage

### ISSUE THREAD

**Issue by jakoss** [ReactiveCircus/FlowBinding#106]
Hi,

LeakCanary just showed me this:
![image](https://user-images.githubusercontent.com/3933348/92104130-34f33500-ede1-11ea-9209-e44be114e6fc.png)

It seems like the root of the leak is the lifecycle registry:
![image](https://user-images.githubusercontent.com/3933348/92104186-49cfc880-ede1-11ea-9522-bf094be82831.png)

Do you an idea why this is happening?

The code that caused that is:
```kotlin
binding.goBtn.clicks()
        .onEach { navigateToAnotherFragment() }
        .launchIn(lifecycleScope)
```

**Comment by ychescale9** [comment]
In a `Fragment` you should use `viewLifecycleOwner.lifecycleScope` instead of `lifecycleScope`. That's the only issue as far as I can see.

BTW the full leakcanary stacktrace is also available in logcat so it'd be easier to share that instead of screenshots 😄 .

Please let me know if that fixes the leak for you.

**Comment by jakoss** [comment]
Wow, didn't know that `viewLifecycleOwner` has it's own coroutine scope. I learned something new, that's always good.

I can confirm that this indeed solves the issue
