### ISSUE TITLE
[Feature Request] ViewPager bindings

### ISSUE THREAD

**Issue by arkon** [ReactiveCircus/FlowBinding#86]
So I'm aware there's [bindings for ViewPager2](https://github.com/ReactiveCircus/FlowBinding/tree/master/flowbinding-viewpager2), but unfortunately I'm stuck using the "original" ViewPager (`androidx.viewpager.widget.ViewPager`).

Would it be possible to add a module for that too?

**Comment by ychescale9** [comment]
Hi, thanks for the request. Yes I don't see why we can't add binding for legacy the `ViewPaging`.

I'd very much appreciate contribution for this one as this is likely not something most users want and I need to work on higher priority stuff at the moment.

Otherwise I should be able to get to this in the next ~ 2 weeks if you can wait 😄

**Comment by arkon** [comment]
I wanted to see if I could contribute to it, but it seems like this project requires a canary version of AS. :(

**Comment by ychescale9** [comment]
Sorry I've been pretty aggressive with upgrading the tools. I'll try to prioritize this.

**Comment by arkon** [comment]
Thanks a bunch!

**Comment by ychescale9** [comment]
This is now available on Maven Central version `0.11.0`.

**Comment by ychescale9** [comment]
Sorry there seems to be an issue with publishing `0.11.0`, working on a fix.

**Comment by ychescale9** [comment]
`0.11.1` is out which should work.
